#!/bin/bash
# ------------------------------------------------------------------------------
# 
# File: trash
# Author: Gabe Gonzalez
#         
# Brief: Delete files, list the contents of the trash, recover previously
#        deleted files, and more.
# 
# ------------------------------------------------------------------------------

##
# Source utilities.
##
. "io.sh"

##
# Files/directories
##
TRASH_SHARE_DIR="${HOME}/.local/share/${PROJECT}"

##
# Options.
##
VERBOSE=true
DELETE=
EMPTY=
INSTALL=
LIST=
LOCATION=
RECOVER=
SIZE=
UNINSTALL=

##
# Exit statuses.
##
EXIT_NO_OPT_ENTERED=10
EXIT_TRASH_DOES_NOT_EXIST=11
EXIT_TRASH_RECOVER_FILE_NOT_FOUND=12
EXIT_TRASH_PROMPT_INDEX_INVALID=13

##
# Trash Can.
##
main()
{
    local short="hlLr:s"
    local long="help,empty,install,list,location,recover:,size,uninstall"
    if [ "${1}" == "-d" -o "${1}" == "--delete" ]
    then
        shift
        trash_delete "${@}"
        exit $?
    fi

    cli_parse "${PROJECT}" "${short}" "${long}" "${@}"

    while true
    do
        case "${1}" in
            -h|--help)
                usage
                exit 0
                ;;

            --empty)
                EMPTY=true
                ;;

            --install)
                INSTALL=true
                ;;

            -l|--list)
                LIST=
                ;;

            -L|--location)
                LOCATION=true
                ;;

            -r|--recover)
                shift
                RECOVER="${1}"
                ;;

            -s|--size)
                SIZE=true
                ;;

            --uninstall)
                UNINSTALL=true
                ;;

            --)
                break
                ;;

            *)
                break
                ;;
        esac
        shift
    done

    # Run checks
    if [ ! -d "${TRASH_SHARE_DIR}" -a -z "${INSTALL}" ]
    then
        print_err "Trash has not been installed yet. See --install for more info."
        exit ${EXIT_TRASH_DOES_NOT_EXIST}
    fi

    # Run options
    if [ -n "${EMPTY}" ]
    then
        trash_empty
    elif [ -n "${INSTALL}" ]
    then
        trash_install
    elif [ -n "${LIST}" ]
    then
        trash_list
    elif [ -n "${LOCATION}" ]
    then
        trash_location
    elif [ -n "${RECOVER}" ]
    then
        trash_recover "${RECOVER}"
    elif [ -n "${SIZE}" ]
    then
        trash_size
    elif [ -n "${UNINSTALL}" ]
    then
        trash_uninstall
    else
        usage
        exit ${EXIT_NO_OPT_ENTERED}
    fi

    exit $?
}

##
# Print program usage.
##
usage()
{
    echo "Usage: ${PROJECT} [options]"
    echo 
    echo "Options:"
    echo "    -h, --help"
    echo "        Print program usage."
    echo 
    echo "    -d, --delete=<files>"
    echo "        Delete one or more files."
    echo 
    echo "    --empty"
    echo "        Empty the trash can."
    echo 
    echo "    --install"
    echo "        Install the trash can."
    echo 
    echo "    -l, --list"
    echo "        List the contents of the trash can."
    echo 
    echo "    -L, --location"
    echo "        Print the location of the trash can."
    echo 
    echo "    -r, --recover=<file>"
    echo "        Recover a file from the trash can."
    echo 
    echo "    -s, --size"
    echo "        Print the size of the trash can."
    echo 
    echo "    --uninstall"
    echo "        Uninstall the trash can."
    echo 
}

##
# Install the trash can.
##
trash_install()
{
    print_info "Installing the trash can."
    mkdir -pv "${TRASH_SHARE_DIR}"
    return $?
}

##
# Delete the input file(s) by moving them to the trash can.
##
trash_delete()
{
    local dest="${TRASH_SHARE_DIR}"/$(date +%Y-%m-%d)
    local now=$(date +%H%M%S)
    local file=
    for file in "${@}"
    do
        if [ ! -e "${file}" ]
        then
            print_err "File '${file}' does not exist."
            continue
        fi
        if [ ! -d "${dest}" ]
        then
            mkdir -p "${dest}"
        fi
        print_info "Deleting '${file}'."
        local name=$(basename "${file}")-"${now}"
        mv "${file}" "${dest}/${name}"
    done
    return $?
}

##
# Empty the trash can.
##
trash_empty()
{
    local response=
    echo "Are you sure you want to empty the trash can?"
    read -p "> " response
    case "${response}" in
        y|Y|yes|Yes|YES)
            print_info "Emptying trash can."
            rm -rfv "${TRASH_SHARE_DIR}"/*
            ;;
        *)
            print_info "Exiting."
            ;;
    esac
    return $?
}

##
# List the contents of the trash.
##
trash_list()
{
    builtin cd "${TRASH_SHARE_DIR}"
    find *
    return $?
}

##
# Print the location of the trash.
##
trash_location()
{
    echo "Trash Location: '${TRASH_SHARE_DIR}'"
    return $?
}

##
# Recover a deleted file.
##
trash_recover()
{
    local file="${1}"
    local IFS=$'\n'
    local matches=($(trash_recovery_get_matches "${file}"))
    local index=
    local fullrecfile=
    local baserecfile=
    trash_recovery_prompt "${matches[@]}" || return $?
    read -p "> " index
    trash_recovery_prompt_valid "${index}" "${#matches[@]}"
    fullrecfile="${matches[$[${index}-1]]}"
    baserecfile=$(basename "${fullrecfile}")
    baserecfile="${baserecfile%-*}"
    echo 
    print_info "Recovering '${baserecfile}'."
    mv "${TRASH_SHARE_DIR}/${fullrecfile}" "${baserecfile}"
}

##
# Print the size of the trash can.
##
trash_size()
{
    local size=$(du -sh "${TRASH_SHARE_DIR}" 2> /dev/null | awk '{ print $1 }')
    echo "Trash Size: ${size}"
    return $?
}

##
# Uninstall the trash can.
##
trash_uninstall()
{
    print_info "Uninstalling trash can at: '${TRASH_SHARE_DIR}'."
    rm -rf "${TRASH_SHARE_DIR}"
    return $?
}

##
# Prompt user for which file to recover.
##
trash_recovery_prompt()
{
    local matches=("${@}")
    if [ $? -ne 0 ]
    then
        print_err "No files matching '${file}' found."
        return ${EXIT_TRASH_RECOVER_FILE_NOT_FOUND}
    fi

    echo "Which file would you like to recover?"
    echo
    local len=$(echo -n "${#matches[@]}" | wc -c)
    local i=1
    local m=
    for m in "${matches[@]}"
    do
        local tsdate="${m%%/*}"
        local substring="${m/${tsdate}\//}"
        local deletedfile="${substring%%/*}"
        local tstime="${deletedfile##*-}"
        local ts="${tsdate} ${tstime:0:2}:${tstime:2:2}:${tstime:4:2}"
        local timestamp=$(date -d "${ts}" +"%a %b %d %_I:%M:%S %p")
        local name=$(basename "${m}")
        name="${name/-${tstime}/}"
        printf "%${len}d: %s | %s\n" "${i}" "${timestamp}" "${name}"
        i=$[ ${i} + 1 ]
    done
}

##
# Return file recovery matches.
##
trash_recovery_get_matches()
{
    builtin cd "${TRASH_SHARE_DIR}"
    local file="${1}"
    local IFS=$'\n'
    find * -name "*${file}*"
}

##
# Verify recovery file index is valid.
##
trash_recovery_prompt_valid()
{
    local index="${1}"
    local max="${2}"
    if [ -z "${index}" ]
    then
        print_info "Exiting."
        return ${EXIT_SUCCESS}
    fi
    if ! is_integer "${index}" || \
        [ ${index} -lt 1 -o ${index} -gt ${max} ]
    then
        print_err "Unable to recover file: Invalid value entered."
        return ${EXIT_TRASH_PROMPT_INDEX_INVALID}
    fi

}

##
# Run the script.
##
main "${@}"
